# Generated by Django 3.1.7 on 2021-02-22 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_coffins_urns'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coffins',
            new_name='Coffin',
        ),
        migrations.RenameModel(
            old_name='Urns',
            new_name='Urn',
        ),
    ]
